install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set MINGWDIR=C:\Qt\Tools\mingw530_32
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin;
  
build_script:
  - qmake rgbtest.pro
  - mingw32-make
  
after_build:
  - windeployqt release\rgbtest.exe --dir rgbtestRelease
  - cp data\rgbtest.svg.png rgbtestRelease
  - cp release\rgbtest.exe rgbtestRelease
  - 7z a rgbtest.zip %APPVEYOR_BUILD_FOLDER%\rgbtestRelease\*

artifacts:
- path: rgbtest.zip
  name: rgbtest


#after_build:
#  - 

#nuget test off

#build:
#  publish_nuget: true
#  publish_nuget_symbols: true
#  
#after_build:
#  - nuget pack rgbtest.nuspec -Verbosity Detailed -Version %APPVEYOR_BUILD_VERSION%
#  
#artifacts:
#- path: '**\*.nupkg'
#  name: rgbtest

