install:
  - set QTDIR=C:\Qt\5.9\mingw53_32
  - set MINGWDIR=C:\Qt\Tools\mingw530_32
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin;

before_build:
  - ECHO #define FVER4 %APPVEYOR_BUILD_NUMBER% > ver.h
  - type ver.h
  
build_script:
  - qmake rgbtest.pro
  - mingw32-make
  
after_build:
  - windeployqt release\rgbtest.exe --dir rgbtestRelease
  - cp data\rgbtest.svg.png rgbtestRelease
  - cp release\rgbtest.exe rgbtestRelease
  - 7z a rgbtest.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\rgbtestRelease\*

artifacts:
- path: rgbtest.%APPVEYOR_BUILD_VERSION%.zip
  name: rgbtest.%APPVEYOR_BUILD_VERSION%

- path: release\rgbtest.exe
  name: rgbtest.exe.%APPVEYOR_BUILD_VERSION%

#after_build:
#  - 

#nuget test off

#build:
#  publish_nuget: true
#  publish_nuget_symbols: true
#  
#after_build:
#  - nuget pack rgbtest.nuspec -Verbosity Detailed -Version %APPVEYOR_BUILD_VERSION%
#  
#artifacts:
#- path: '**\*.nupkg'
#  name: rgbtest

